### PR TITLE
feat: add commit lints for consistency

### PR DESCRIPTION
**Pull request by lwhiteley**

### CODE REVIEW

**Comment by iambumblehead** [comment]
@lwhiteley will the husky hook catch my bad commit messages and block them for me?

**Comment by lwhiteley** [comment]
> @lwhiteley will the husky hook catch my bad commit messages and block them for me?

yes it will

**Comment by iambumblehead** [comment]
:+1: :apple: approved

**Comment by lwhiteley** [comment]
can you also only allow 'squash and merge' pull request acceptance?

**Pull request merged**
