### PR TITLE
fix: remove react from distributed bundle

### PR DESCRIPTION
**Pull request by lwhiteley**
relates to #96

### CODE REVIEW

**Comment by lwhiteley** [comment]
@dalmo3  @iambumblehead 

please pull branch locally and let me know if it. works

**Comment by dalmo3** [comment]
Still no luck. Same error. Invalid hook call in `Dropdown.tsx`. Tried with npm 7 like you suggested and yarn v1.

**Comment by lwhiteley** [comment]
hmm doesnt add up .. i used same env and worked.

Steps:
`git checkout fix-lockfile`

Tests 1:
- deleted node_modules
- `yarn`
- `yarn start`

Tests 2:
- deleted node_modules
- `npm i --legacy-peer-deps`
- `npm start`

Both worked

Screenshot 2021-05-26 at 7 59 28 AM

**Comment by iambumblehead** [comment]
I just discovered this PR... I haven't tried running @dalmo3's sample app on the linux machine but I'll try it and see how it goes. There's a similar error that occurs when running storybook https://github.com/storybookjs/storybook/issues/10662#issuecomment-848399964 but the error only occurs on the mac machine --storybook runs fine on the linux machine

| mac | linux |
| ------------- | ------------- |
| node v16.0.0  | node v16.2.0  |
| npm 7.10.0  | npm 7.14.0 |
| Error: Invalid hook call | ?? |

**Comment by lwhiteley** [comment]
still no issues for me

| mac | 
| ------------- | 
| node v16.2.0  | 
| npm 7.14.0  | 
| all fine |

**Comment by lwhiteley** [comment]
> many other people are recently affected by the same sort of problems facebook/react#13991

yup but this issue is from 2018.
Im not certain if im reproducing the issue as you guys are doing it.

can you give detailed instructions and what you are using to test the issue

**Comment by iambumblehead** [comment]
[react-dropdown-now-app.zip](https://github.com/iambumblehead/react-dropdown-now/files/6544874/react-dropdown-now-app.zip)

This is a version of @dalmo3's app. To use it, unzip it and npm install && npm start.

To test this branch there `rm node_modules/react-dropdown-now` then clone this branch to the same place, npm install && npm build.

**Comment by iambumblehead** [comment]
@lwhiteley the bottom, recent half of the discussion in that thread is from the last 30 days  or so https://github.com/facebook/react/issues/13991#issuecomment-829626429

**Comment by lwhiteley** [comment]
@iambumblehead 

in the bundle you have

`"react-dropdown-now": "6.0.0",`. shouldnt this be `"react-dropdown-now": "../react-dropdown-now",` ?

**Comment by lwhiteley** [comment]
ok now i reproduce. will continue from here later

**Comment by lwhiteley** [comment]
it seems to not be installing changes from the branch somwhow and still old version

i removed the useMemo but it still shows that code 
Screenshot 2021-05-26 at 10 18 31 AM

**Comment by lwhiteley** [comment]
hmm i didnt rebuild my local dist folder..will test again soon

**Comment by iambumblehead** [comment]
Screenshot from 2021-05-26 01-40-51

the @reach/router react dependency (from storybook) makes it impossible to control the react dependencies. We used the work-around described here https://github.com/reach/router/pull/432#issuecomment-785135132 in order to install storybook with the react17

**Comment by lwhiteley** [comment]
yup but when you install the component as a dependency, storybook isnt installed so something else is the issue

**Comment by lwhiteley** [comment]
so i confirmed that our bundle had a react version inside and this removes it..however your setup with npm link still has issue so ill fix this up and we do a patch release to test correctly

**Comment by lwhiteley** [comment]
i also confirmed the test app is working actually

instead of using npm link
- i just installed v6.0.0
- npm run build on this local branch
- copied the dist folder into the node_module of the test app

**Review by iambumblehead — APPROVED** [review]

**Comment by lwhiteley** [comment]
k @iambumblehead .. you can do a patch release

Thanks

**Comment by iambumblehead** [comment]
@lwhiteley your latest branch works here after removing react-dropdown-now's node modules directory
```
bumble@duck react-dropdown-now-app水$ cd node_modules/react-dropdown-now/
bumble@duck react-dropdown-now水$ mv node_modules node_modulesOLD
```
great! :)

**Pull request merged**
