### PR TITLE
refactor!: options rendering updates

### PR DESCRIPTION
**Pull request by lwhiteley**
**Issue:**
code was too complex and the data structure being used internally was hard to determine. At some points in the code the option value kept mutating/re-parsed based on `typeof(option)`.
 
By using only one structure throughout the components (parse once at the beginning):
- it makes the components easier to manage and maintain. 
- The expected data structure is always the same.
- Also was able to reduce recursive and complex functions

**Changes:** 
- change flow of how options are parsed.
  - now options are parsed once and sub components use only the parsed options
- onChange now always returns an object `{ value, id, label, view, className }`, where `id`, `view` and `className` are only returned when defined
- return event object as second arg for onChange
- no longer need to specify `type: 'group'`
  - once the option has an `items[]` prop, we assume it is a group
- introduce optional `option.id` and `matcher` properties.
  - when `option.value` is not a string|number, the id can be set to uniquely identify the option
  - `matcher` function can be used to identify the selected option
- remove license text from readme, only specify type

you can see the helpers tests to see what the internal data structure is like

internal data structures:
```js
  export enum RenderType {
    OPTION,
    LABEL,
  }
  export interface RenderItem {
    option: Option;
    id: string;
    index: number;
    type: RenderType;
  }
```

### CODE REVIEW

**Comment by lwhiteley** [comment]
@iambumblehead i just need to add an additional test but you can start to review

**Comment by lwhiteley** [comment]
@iambumblehead  all ready for a review

**Comment by iambumblehead** [comment]
thank you! this will be terrific! I will review...

**Comment by iambumblehead** [comment]
We could use this helper function to verify values more strictly. This would allow us to not make too many changes to the component, allow us to forego an additional id property and allow us to avoid managing extra state within the component 

https://github.com/iambumblehead/react-dropdown-now/blob/develop/src/helpers.js#L2

however, if you have solution that works here that is OK as well

**Comment by iambumblehead** [comment]
I'm not sure the lodash get lookups are necessary -- the options structures are small and definition lookups are shallow

**Comment by iambumblehead** [comment]
if you are OK with the above considerations @lwhiteley ... feel free to merge this. I do not find any technical problems with the changes here.

**Comment by lwhiteley** [comment]
> https://github.com/iambumblehead/react-dropdown-now/blob/develop/src/helpers.js#L2

i was thinking of removing it later actually. once the values are passed into the object structure, we can assume they should be used as is so it is serving little purpose currently. the consumer of the component should ensure the desired values are correct. The value property IMO can be anything the user wants to select against. it could be a complex object

> I'm not sure the lodash get lookups are necessary

for now it keeps the code clean and simple. if we move to TS we can take advantage of null-coalescing and remove them

ill go ahead and merge to get most of these changes in. ill do some more testing as well and try to release to npm around sunday if all is well

**Comment by iambumblehead** [comment]
@lwhiteley thanks for the thoughtful (and convincing) response :)

**Pull request merged**
