### PR TITLE
chore: increment dependencies. rm lint-failing aria-haspopup

### PR DESCRIPTION
**Pull request by iambumblehead**
please review

### CODE REVIEW

**Comment by iambumblehead** [comment]
The pr lint doesn't tell me how to make a passing pr title

**Comment by iambumblehead** [comment]
@lwhiteley please review :)

**Comment by lwhiteley** [comment]
I'll review a bit later today. Still quite early for me 🤠

**Comment by iambumblehead** [comment]
it seems the aria role should be changed to button and haspopup should be used  https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html#rps1_label

however, changing the control in that way, the linter then requires the control be updated so that it can take focus. A separate MR should probably be made for the haspopup aria label and so the attribute is removed altogether to pass the lint here.

**Review by lwhiteley — APPROVED** [review]

**Pull request merged**
