### PR TITLE
Develop merged master

### PR DESCRIPTION
**Pull request by iambumblehead**

### CODE REVIEW

**Comment by iambumblehead** [comment]
How should we get develop into master nicely.

This branch in this PR was created from master. After that, develop was _pulled_ into this branch and merge conflicts were resolved. Disabling the commit lint was necessary to get the pipeline to pass. This would probably mess up the commit history...

What do you think @lwhiteley?

**Comment by lwhiteley** [comment]
for now we could just cherry-pick the changes in .. but i think master needs to be rebased somehow first .. then we should only squash and merge to master to ensure the history isnt tampered with.

easiest way is to delete master and recreate it from develop

**Comment by lwhiteley** [comment]
so i would close this PR as it would also tamper with develop history

**Comment by iambumblehead** [comment]
ok @lwhiteley I'm glad you are here

**Pull request closed without merging**
