### PR TITLE
fix: no onSelect event when same item selected

### PR DESCRIPTION
**Pull request by iambumblehead**

### CODE REVIEW

**Comment by iambumblehead** [comment]
@lwhiteley changes here are for this ticket https://github.com/iambumblehead/react-dropdown-now/issues/96

**Comment by iambumblehead** [comment]
@lwhiteley the more I think about it... the current behaviour _before_ the changes here seems correct. Maybe we should close the issue and update the test to verify that onSelect is called even when the value is the same.

What do you think?

**Comment by lwhiteley** [comment]
Think the issue is that the events should not be triggered when there is no user interaction

**Comment by iambumblehead** [comment]
@lwhiteley I had the same impression at first and I even added a test that rendered two dropdowns referencing the same value --changing one dropdown did not change the value or trigger events at the other dropdown. I could re-add that test.

**Comment by iambumblehead** [comment]
@lwhiteley upon second thought, the two-dropdowns tests used a primitive value "one" and maybe using an object value instead triggers the onChange event.

**Comment by iambumblehead** [comment]
I'll add the two-dropdowns test in a few hours

**Comment by iambumblehead** [comment]
@lwhiteley please review

**Comment by iambumblehead** [comment]
@lwhiteley I was able to reproduce the issue. Changing the value of the second dropdown triggered onChange at the first dropdown. To resolve it, the dropdown reads the event target to detect if the event originates at the dropdown.

**Comment by iambumblehead** [comment]
There could issues if the dropdown later needed to support keyboard selection and input, but if you're OK with the current change I will be too.

**Comment by iambumblehead** [comment]
do you use Matrix @lwhiteley? https://matrix.org/clients/

**Comment by lwhiteley** [comment]
> do you use Matrix @lwhiteley? https://matrix.org/clients/

never heard of it. what would be the purpose of it?

**Review by lwhiteley — APPROVED** [review]
Can go with this for now and maybe review the entire composition in a next major version

**Comment by lwhiteley** [comment]
> never heard of it. what would be the purpose of it?

actually seems i have used it without knowing. i used gitter.im before

**Comment by iambumblehead** [comment]
@lwhiteley this page has a little blurb describing matrix https://tatsumoto-ren.github.io/blog/join-our-community.html

> Matrix is great because it's completely libre and federated, and you don't need an email address, or a phone number to make an account. Just type your name and a password, and you're in! Before you join, install a Matrix client and register an account on any server that is not matrix.org.

I know about it because there are clients for ubuntu touch and gnome3, which I use on my phone and desktop. Also, I like messaging applications and have been building a service that follows the matrix spec in many parts. I would like to be your friend on Matrix or another messaging system.

**Comment by lwhiteley** [comment]
can chat privately on https://gitter.im/

and discuss further

**Comment by iambumblehead** [comment]
I signed in there with my github proifile and if I type "lwhi" or "whit" it doesn't auto-complete "lwhitely" there.

**Pull request merged**
