### PR TITLE
chore: use wildcard for dist dir

### LINKED ISSUE #11: Bug! Module not found: Can't resolve './Dropdown'
Hello, thanks for making this fork of `react-dropdown`.

I was using version `1.0.3` and everything was working fine, now the latest version is causing this error:

```
~/myRepo/node_modules/react-dropdown-now/dist/index.js
Module not found: Can't resolve './Dropdown' in '~/myRepo/node_modules/react-dropdown-now/dist'
```

Please help.

### PR DESCRIPTION
**Pull request by lwhiteley**
fixes #11

### CODE REVIEW

**Comment by iambumblehead** [comment]
perfect

**Comment by lwhiteley** [comment]
ok you can go ahead and do another release now @iambumblehead

**Comment by iambumblehead** [comment]
@lwhiteley ok I will do it

**Comment by iambumblehead** [comment]
Screenshot from 2020-02-15 10-44-24

**Comment by lwhiteley** [comment]
looks good 👍

**Pull request merged**
