### PR TITLE
feat: add option disabled prop

### PR DESCRIPTION
**Pull request by lwhiteley**
cc: @Ploppz

```js
options: [
    { value: 0, label: 'Cant Touch this!', disabled: true },
    { value: 1, label: 'One' },
    {
      name: 'group test',
      items: [
        { value: 'five', label: 'Not this either', disabled: true  },
        { value: 'six', label: 'Six' },
      ],
    },
  ],
```

### CODE REVIEW

**Comment by iambumblehead** [comment]
@lwhiteley this looks great to me. I'm checking it out locally and will :+1: after I smoke test

**Comment by iambumblehead** [comment]
Screenshot from 2020-10-31 22-53-26

looks perfecc

**Comment by iambumblehead** [comment]
still october here in los angeles

**Comment by lwhiteley** [comment]
ah i see lol .. its now November for me in Germany 😸

**Pull request merged**
