### PR TITLE
refactor: switch from enzyme to react-testing-lib

### PR DESCRIPTION
**Pull request by lwhiteley**
Changes:
- use jest as test runner instead of ava
- switch from enzyme to react-testing-library

### CODE REVIEW

**Comment by lwhiteley** [comment]
also quick favour can you add `hacktoberfest` to the repository topics.

you can also check it out if you want to register: https://hacktoberfest.digitalocean.com/

**Comment by iambumblehead** [comment]
@lwhiteley the hacktoberfest topic is added

**Comment by iambumblehead** [comment]
I don't know much about jest vs ava but the changes look safe to me. Feel free to squash and merge :+1:

**Review by iambumblehead — APPROVED** [review]

**Comment by lwhiteley** [comment]
sorry the reason for the change is really to use react-testing library which works better with jest.

it currently handles testing hooks better than enzyme and is more widely used now

**Pull request merged**
