### PR TITLE
feat: add pull request preview workflow

### PR DESCRIPTION
**Pull request by lwhiteley**
@iambumblehead 

Let's try to use PR previews
in order to do this.

- [x] you would need to create a surge account
- [x] get a token `$ surge token`
- [x] create a secret in the github project `SURGE_TOKEN` with the value you got
- [x] When all that is done we can then check it works

See links:
- https://github.com/marketplace/actions/surge-pr-preview
- https://surge.sh/help/getting-started-with-surge

### CODE REVIEW

**Comment by lwhiteley** [comment]
sweet.. seems. to work 😸 

Screenshot 2020-11-02 at 11 40 56

**Comment by iambumblehead** [comment]
Screenshot from 2020-11-02 03-03-49
hm

**Comment by lwhiteley** [comment]
What version of node are you running?

**Comment by iambumblehead** [comment]
node 15.0.1

**Comment by lwhiteley** [comment]
try 14, hopefully you are using nvm and this is a simple switch

**Comment by iambumblehead** [comment]
my work computer uses node 14. I'll use that "tomorrow" eg, in a few hours :)

**Comment by lwhiteley** [comment]
i see the same warning as you and still able to create the account.. 

try typing your email and hit enter

**Comment by iambumblehead** [comment]
super cool @lwhiteley

**Pull request merged**
