### PR TITLE
componentize option element

### PR DESCRIPTION
**Pull request by iambumblehead**
[Componentize the option element][0] and [more tests.][1]

[0]: https://github.com/iambumblehead/react-dropdown-now/compare/componentize-option-element?expand=1#diff-168726dbe96b3ce427e7fedce31bb0bc
[1]: https://github.com/iambumblehead/react-dropdown-now/compare/componentize-option-element?expand=1#diff-40a1a51aaea84e5e8bd25f730b5f329b

### CODE REVIEW

**Comment by iambumblehead** [comment]
@guischafer, politely, would you review my changes here? The option element is changed to a function component and some tests are added.

**Comment by lwhiteley** [comment]
i can take a stab at reviewing later

but some comments i have.

you should probably create multiple pull requests split into different concerns
1. pruning git tracked folders
1. componentize option element
1. cleaning up code

as this would be easier to review and test separately

also you should setup your git config to have your username and email

```shell
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

you can leave this PR open until all other concerns are merged just to keep track off all that needs to be done

**Comment by iambumblehead** [comment]
@lwhiteley I will update my git config details. Thank you for your comments and advice.

**Comment by lwhiteley** [comment]
yup that should be fine now

**Comment by lwhiteley** [comment]
when you have time, you can go ahead and create PRs with the concepts you have here and ill review.

**Comment by iambumblehead** [comment]
my schedule is somewhat full for the next 8-10 hours but after that I will make at least one PR

**Comment by lwhiteley** [comment]
think we can close this now

**Pull request closed without merging**
