### PR TITLE
chore: add git config details

### PR DESCRIPTION
**Pull request by iambumblehead**
I'm hoping this will resolve the pipeline error seen here https://github.com/iambumblehead/react-dropdown-now/runs/1336547909
```bash
info => Output directory: /home/runner/work/react-dropdown-now/react-dropdown-now/docs
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az121-113.df0a0lltdjiezknqffi5jqff2f.cx.internal.cloudapp.net>) not allowed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-dropdown-now@4.1.0 deploy: `npm run build-storybook && gh-pages -d docs -m 'chore: deploy docs'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-dropdown-now@4.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-31T18_25_58_485Z-debug.log
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Comment by lwhiteley** [comment]
I'll test in a bit

**Comment by iambumblehead** [comment]
feel free to use your email there if you prefer. I used mine there just to get things going.

**Comment by iambumblehead** [comment]
oh cool you've made it so that isn't needed -- that looks awesome

**Comment by iambumblehead** [comment]
:+1:

**Comment by iambumblehead** [comment]
:+1:

**Comment by lwhiteley** [comment]
ok i think its done now @iambumblehead

**Review by lwhiteley — APPROVED** [review]

**Pull request merged**
